### ISSUE TITLE
MongooseError: The `uri` parameter to `openUri()` must be a string, got "undefined". Make sure the first parameter to `mongoose.connect()` or `mongoose.createConnection()` is a string.

### ISSUE THREAD

**Issue by DracoMilesX** [wory48/Yuzuki#1]
Trying to create a Dockerfile for the bot but while trying it out I run into the following issue:

```
| MongooseError: The `uri` parameter to `openUri()` must be a string, got "undefined". Make sure the first parameter to `mongoose.connect()` or `mongoose.createConnection()` is a string.
|     at NativeConnection.Connection.openUri (/app/node_modules/mongoose/lib/connection.js:689:11)
|     at /app/node_modules/mongoose/lib/index.js:342:10
|     at /app/node_modules/mongoose/lib/helpers/promiseOrCallback.js:32:5
|     at new Promise (<anonymous>)
|     at promiseOrCallback (/app/node_modules/mongoose/lib/helpers/promiseOrCallback.js:31:10)
|     at Mongoose._promiseOrCallback (/app/node_modules/mongoose/lib/index.js:1176:10)
|     at Mongoose.connect (/app/node_modules/mongoose/lib/index.js:341:20)
|     at Object.<anonymous> (/app/src/index.js:14:10)
|     at Module._compile (node:internal/modules/cjs/loader:1103:14)
|     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
```

This is the mongo uri in the .env:
MONGOOSE=mongodb://test:test@mongodb4/test

Not certain if its related to mongoose/mongo version or the way it tries to connect from within the bot.

**Comment by rilysh** [comment]
It looks like an issue to read `.env` file. Try to add mongodb URI here.
https://github.com/Codes-nopr/Yuzuki/blob/e116e79ccbeab15eed456c36d7a1f0535a02fad6/src/index.js#L14
Replace `process.env.MONGOOSE` with the actual URI.
